# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hst_data_tool.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyqtgraph as pg
import win32api
from tkinter import filedialog as fd
from hst import HST
from pathlib import Path


class Ui_Form(object):

    hst = None

    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(959, 1003)

        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 921, 969))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")

        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")

        self.dateTimeEdit_start = QtWidgets.QDateTimeEdit(self.gridLayoutWidget)
        self.dateTimeEdit_start.setObjectName("dateTimeEdit_start")
        self.gridLayout.addWidget(self.dateTimeEdit_start, 6, 0, 1, 1)

        self.pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 2, 1, 1)



        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)

        self.label_start = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_start.setMaximumSize(QtCore.QSize(16777215, 10))
        self.label_start.setAlignment(QtCore.Qt.AlignCenter)
        self.label_start.setObjectName("label_start")
        self.gridLayout.addWidget(self.label_start, 4, 0, 1, 1)

        self.radioButton = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton.setAutoExclusive(False)
        self.radioButton.setObjectName("radioButton")
        self.gridLayout.addWidget(self.radioButton, 12, 2, 1, 1)

        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 12, 0, 1, 1)

        self.comboBox_drive = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_drive.setObjectName("comboBox_drive")
        self.gridLayout.addWidget(self.comboBox_drive, 11, 1, 1, 1)

        self.comboBox_drive.addItems(win32api.GetLogicalDriveStrings().split('\000')[:-1])

        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)

        self.lineEdit = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 12, 1, 1, 1)

        self.radioButton_2 = QtWidgets.QRadioButton(self.gridLayoutWidget)
        self.radioButton_2.setAutoExclusive(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout.addWidget(self.radioButton_2, 11, 2, 1, 1)

        self.calendarWidget_start = QtWidgets.QCalendarWidget(self.gridLayoutWidget)
        self.calendarWidget_start.setMaximumSize(QtCore.QSize(2000, 200))
        self.calendarWidget_start.setObjectName("calendarWidget_start")
        self.gridLayout.addWidget(self.calendarWidget_start, 7, 0, 1, 1)

        self.dateTimeEdit_end = QtWidgets.QDateTimeEdit(self.gridLayoutWidget)
        self.dateTimeEdit_end.setCalendarPopup(False)
        self.dateTimeEdit_end.setObjectName("dateTimeEdit_end")
        self.gridLayout.addWidget(self.dateTimeEdit_end, 6, 1, 1, 1)

        self.calendarWidget_end = QtWidgets.QCalendarWidget(self.gridLayoutWidget)
        self.calendarWidget_end.setMaximumSize(QtCore.QSize(16777215, 200))
        self.calendarWidget_end.setObjectName("calendarWidget_end")
        self.gridLayout.addWidget(self.calendarWidget_end, 7, 1, 1, 1)

        self.label_end = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_end.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_end.setAlignment(QtCore.Qt.AlignCenter)
        self.label_end.setObjectName("label_end")
        self.gridLayout.addWidget(self.label_end, 4, 1, 1, 1)


        self.graph_start = pg.PlotWidget(self.gridLayoutWidget)
        self.graph_start.setMinimumSize(QtCore.QSize(0, 70))
        self.graph_start.setMaximumSize(QtCore.QSize(16777215, 200))
        self.graph_start.setObjectName("graph_start")
        self.gridLayout.addWidget(self.graph_start, 5, 0, 1, 1)

        self.graph_start.addItem(pg.InfiniteLine())


        self.graph_end = pg.PlotWidget(self.gridLayoutWidget)
        self.graph_end.setMinimumSize(QtCore.QSize(0, 70))
        self.graph_end.setMaximumSize(QtCore.QSize(16777215, 200))
        self.graph_end.setObjectName("graph_end")
        self.gridLayout.addWidget(self.graph_end, 5, 1, 1, 1)

        self.graph_end.addItem(pg.InfiniteLine())



        self.columnView = QtWidgets.QColumnView(self.gridLayoutWidget)
        self.columnView.setObjectName("columnView")
        self.gridLayout.addWidget(self.columnView, 5, 2, 3, 1)

        self.pushButton_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 8, 2, 1, 1)

        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 11, 0, 1, 1)



        self.columnView_2 = QtWidgets.QColumnView(self.gridLayoutWidget)
        self.columnView_2.setObjectName("columnView_2")
        self.gridLayout.addWidget(self.columnView_2, 5, 3, 3, 1)




        #self.listWidget = QtWidgets.QListWidget(self.gridLayoutWidget)
        self.graph = pg.PlotWidget(self.gridLayoutWidget)
        self.graph.setMinimumSize(QtCore.QSize(0, 150))
        self.graph.setMaximumSize(QtCore.QSize(16777215, 300))
        self.graph.setObjectName("graph")
        self.gridLayout.addWidget(self.graph, 1, 0, 1, 4)

        self.graph.addItem(pg.InfiniteLine(movable=True))
        self.graph.addItem(pg.InfiniteLine(movable=True))


        self.progressBar = QtWidgets.QProgressBar(self.gridLayoutWidget)
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 13, 0, 1, 4)

        self.retranslateUi(Form)

        self.calendarWidget_start.activated['QDate'].connect(self.dateTimeEdit_start.setDate)
        self.calendarWidget_end.activated['QDate'].connect(self.dateTimeEdit_end.setDate)
        self.dateTimeEdit_start.dateChanged['QDate'].connect(self.calendarWidget_start.setSelectedDate)
        self.dateTimeEdit_end.dateChanged['QDate'].connect(self.calendarWidget_end.setSelectedDate)

        self.pushButton.clicked.connect(self.import_HST)

        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "ADD HST"))
        self.label_start.setText(_translate("Form", "START"))
        self.radioButton.setText(_translate("Form", "Enabled"))
        self.label_5.setText(_translate("Form", "modPath"))
        self.label_2.setText(_translate("Form", "Select HST"))
        self.radioButton_2.setText(_translate("Form", "Enabled"))
        self.label_end.setText(_translate("Form", "END"))
        self.pushButton_2.setText(_translate("Form", "PushButton"))
        self.label_3.setText(_translate("Form", "Drive"))


    def import_HST(self):
        print('yes')

        self.hst = HST()

        if self.radioButton_2.isChecked():
            self.hst.drive = 'C'   # todo edit

        if self.radioButton.isChecked():
            print(self.lineEdit.text())
            self.hst.repath = Path(self.lineEdit.text())   # todo edit

        self.hst.load(fd.askopenfilename())

        self.load_data()


    def load_data(self):

        self.graph.addItem(pg.plot(self.hst[:].get_data()))

        # hst = HST()
        #
        # hst.drive = _drive
        #
        # # repath to the following dir, this repath replaces the paths
        # # within the HST_one
        # hst.repath = inputPath_2
        #
        # # load
        # hst.load(inputFile_2)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
